# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"instance_sort": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://asvcode.github.io/med/"

git_url = "https://github.com/asvcode/med/tree/master/"

def custom_doc_links(name): return None
